---
# This playbook provides an example on how to use a "When" conditional  

- hosts: webservers
  become: True

  tasks:
    - name: install apache2
      apt: name=apache2 state=latest
      when: ansible_pkg_mgr == "apt"
      

    - name: install httpd
      yum: name=httpd state=latest
      when: ansible_pkg_mgr == "yum"
     
