---
# This play ignores errors when install pkgs on hosts with different OS 
# Shown below is an example of a pkg (vsftpd) installed on an ubuntu hosts

- hosts: # add hosts
  become: True
  tasks:
    - name: install vsftpd on ubuntu
      apt: name=vsftpd update_cache=yes state=latest
      ignore_errors: yes
      notify: start vsftpd

    - name: install vsftpd
      yum: name=vsftpd state=latest
      ignore_errors: yes
      notify: start vsftpd

  handlers:
    - name: start vsftpd
      service: name=vsftpd enabled=yes state=started


