---
# This playbook is used to install individual and recommended
# packages on Ubuntu hosts. Add desired pkg items to empty pkg list.


- hosts: # add host(s)
  become: yes
  vars:
    pkg: []

  tasks: 
    - name: Install pkgs
      apt:
        name: "{{item}}"
        update_cache: yes
        state: latest
        install_recommends: yes
      loop: "{{pkg}}"
      when: ansible_os_family == "Debian"
         
      


